#Here are the functions for preprocessing the binary model for edibility
###############IMPORTS#######################
from keras.preprocessing.image import ImageDataGenerator
from sklearn.utils import resample
import tensorflow as tf
from keras import layers, models
import pandas as pd
import numpy as np
from keras.callbacks import EarlyStopping
from PIL import Image
import os, zipfile, requests

#creating a function to add edibility criteria and drop duplicates
def add_edibility(df) :
    df=df.drop_duplicates()
    species_to_label = {
    "Agaricus augustus": 0,
    "Agaricus xanthodermus": 1,
    "Amanita amerirubescens": 1,
    "Amanita augusta": 1,
    "Amanita brunnescens": 1,
    "Amanita calyptroderma": 0,
    "Amanita citrina": 1,
    "Amanita flavoconia": 1,
    "Amanita muscaria": 1,
    "Amanita pantherina": 1,
    "Amanita persicina": 1,
    "Amanita phalloides": 1,
    "Amanita rubescens": 1,
    "Amanita velosa": 1,
    "Apioperdon pyriforme": 0,
    "Armillaria borealis": 0,
    "Armillaria mellea": 0,
    "Armillaria tabescens": 0,
    "Artomyces pyxidatus": 0,
    "Bjerkandera adusta": 1,
    "Bolbitius titubans": 1,
    "Boletus edulis": 0,
    "Boletus pallidus": 0,
    "Boletus reticulatus": 0,
    "Boletus rex-veris": 0,
    "Calocera viscosa": 1,
    "Calycina citrina": 1,
    "Cantharellus californicus": 0,
    "Cantharellus cibarius": 0,
    "Cantharellus cinnabarinus": 0,
    "Cerioporus squamosus": 0,
    "Cetraria islandica": 0,
    "Chlorociboria aeruginascens": 1,
    "Chlorophyllum brunneum": 1,
    "Chlorophyllum molybdites": 1,
    "Chondrostereum purpureum": 1,
    "Cladonia fimbriata": 1,
    "Cladonia rangiferina": 0,
    "Cladonia stellaris": 0,
    "Clitocybe nebularis": 1,
    "Clitocybe nuda": 0,
    "Coltricia perennis": 1,
    "Coprinellus disseminatus": 1,
    "Coprinellus micaceus": 0,
    "Coprinopsis atramentaria": 1,
    "Coprinopsis lagopus": 1,
    "Coprinus comatus": 0,
    "Crucibulum laeve": 1,
    "Cryptoporus volvatus": 1,
    "Daedaleopsis confragosa": 1,
    "Daedaleopsis tricolor": 1,
    "Entoloma abortivum": 0,
    "Evernia mesomorpha": 1,
    "Evernia prunastri": 1,
    "Flammulina velutipes": 0,
    "Fomes fomentarius": 1,
    "Fomitopsis betulina": 1,
    "Fomitopsis mounceae": 1,
    "Fomitopsis pinicola": 1,
    "Galerina marginata": 1,
    "Ganoderma applanatum": 1,
    "Ganoderma curtisii": 1,
    "Ganoderma oregonense": 1,
    "Ganoderma tsugae": 0,
    "Gliophorus psittacinus": 1,
    "Gloeophyllum sepiarium": 1,
    "Graphis scripta": 1,
    "Grifola frondosa": 0,
    "Gymnopilus luteofolius": 1,
    "Gyromitra esculenta": 1,
    "Gyromitra gigas": 1,
    "Gyromitra infula": 1,
    "Hericium coralloides": 0,
    "Hericium erinaceus": 0,
    "Hygrophoropsis aurantiaca": 1,
    "Hypholoma fasciculare": 1,
    "Hypholoma lateritium": 0,
    "Hypogymnia physodes": 1,
    "Hypomyces lactifluorum": 0,
    "Imleria badia": 0,
    "Inonotus obliquus": 0,
    "Ischnoderma resinosum": 1,
    "Kuehneromyces mutabilis": 0,
    "Laccaria ochropurpurea": 1,
    "Lactarius deliciosus": 0,
    "Lactarius torminosus": 1,
    "Lactarius turpis": 1,
    "Laetiporus sulphureus": 0,
    "Leccinum albostipitatum": 0,
    "Leccinum aurantiacum": 0,
    "Leccinum scabrum": 0,
    "Leccinum versipelle": 0,
    "Lepista nuda": 0,
    "Leratiomyces ceres": 1,
    "Leucoagaricus americanus": 1,
    "Leucoagaricus leucothites": 0,
    "Lobaria pulmonaria": 1,
    "Lycogala epidendrum": 1,
    "Lycoperdon perlatum": 0,
    "Lycoperdon pyriforme": 0,
    "Macrolepiota procera": 0,
    "Merulius tremellosus": 1,
    "Mutinus ravenelii": 1,
    "Mycena haematopus": 1,
    "Mycena leaiana": 1,
    "Nectria cinnabarina": 1,
    "Omphalotus illudens": 1,
    "Omphalotus olivascens": 1,
    "Panaeolus papilionaceus": 1,
    "Panellus stipticus": 1,
    "Parmelia sulcata": 1,
    "Paxillus involutus": 1,
    "Peltigera aphthosa": 1,
    "Peltigera praetextata": 1,
    "Phaeolus schweinitzii": 1,
    "Phaeophyscia orbicularis": 1,
    "Phallus impudicus": 0,
    "Phellinus igniarius": 1,
    "Phellinus tremulae": 1,
    "Phlebia radiata": 1,
    "Phlebia tremellosa": 1,
    "Pholiota aurivella": 1,
    "Pholiota squarrosa": 1,
    "Phyllotopsis nidulans": 1,
    "Physcia adscendens": 1,
    "Platismatia glauca": 1,
    "Pleurotus ostreatus": 0,
    "Pleurotus pulmonarius": 0,
    "Psathyrella candolleana": 1,
    "Pseudevernia furfuracea": 1,
    "Pseudohydnum gelatinosum": 0,
    "Psilocybe azurescens": 1,
    "Psilocybe caerulescens": 1,
    "Psilocybe cubensis": 1,
    "Psilocybe cyanescens": 1,
    "Psilocybe ovoideocystidiata": 1,
    "Psilocybe pelliculosa": 1,
    "Retiboletus ornatipes": 0,
    "Rhytisma acerinum": 1,
    "Sarcomyxa serotina": 0,
    "Sarcoscypha austriaca": 1,
    "Sarcosoma globosum": 1,
    "Schizophyllum commune": 1,
    "Stereum hirsutum": 1,
    "Stereum ostrea": 1,
    "Stropharia aeruginosa": 1,
    "Stropharia ambigua": 1,
    "Suillus americanus": 0,
    "Suillus granulatus": 0,
    "Suillus grevillei": 0,
    "Suillus luteus": 0,
    "Suillus spraguei": 0,
    "Tapinella atrotomentosa": 1,
    "Trametes betulina": 1,
    "Trametes gibbosa": 1,
    "Trametes hirsuta": 1,
    "Trametes ochracea": 1,
    "Trametes versicolor": 1,
    "Tremella mesenterica": 0,
    "Trichaptum biforme": 1,
    "Tricholoma murrillianum": 0,
    "Tricholomopsis rutilans": 0,
    "Tylopilus felleus": 1,
    "Tylopilus rubrobrunneus": 1,
    "Urnula craterium": 1,
    "Verpa bohemica": 1,
    "Volvopluteus gloiocephalus": 0,
    "Vulpicida pinastri": 1,
    "Xanthoria parietina": 1,
    }
    df["edibility"] = df["label"].map(species_to_label)
    return df

#function to create a generator to use the image_path

def generator(df,x_col,y_col,img_size,batch_size,shuffle) :

    datagen = ImageDataGenerator(rescale=1./255)

    gen = datagen.flow_from_dataframe(
    dataframe=df,
    x_col=x_col,
    y_col=y_col,
    target_size=img_size,
    color_mode="rgb",
    class_mode="categorical",
    batch_size=batch_size,
    shuffle=shuffle,
    )
    return gen

#function for compiling

def model_compiling(model) :
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy','precision','recall'])


#function for fitting
def model_fitting(model,train_data,validation_data,epochs=10) :

    #callbacks
    es = [EarlyStopping(patience=5, restore_best_weights=True, monitor="val_accuracy")]

    #fitting
    history = model.fit(
    train_data,
    validation_data=validation_data,
    epochs=epochs,
    verbose=1,
    callbacks=es
    )

    return history

#function for evaluating
def evaluate_model(model,test_data) :
    evaluation=model.evaluate(test_data)
    return evaluation

################# Functions for the prediction #####################

def preprocess_for_predict(img_path) :
    img=Image.open(img_path)
    img=img.resize((224,224))
    arr=np.array(img).astype('float32')
    arr=arr/255.0
    arr.shape
    arr=np.expand_dims(arr,axis=0)
    return arr

def predict(model,img):
    index_to_class={0: 'Agaricus augustus',
        1: 'Agaricus xanthodermus',
        2: 'Amanita amerirubescens',
        3: 'Amanita augusta',
        4: 'Amanita brunnescens',
        5: 'Amanita calyptroderma',
        6: 'Amanita citrina',
        7: 'Amanita flavoconia',
        8: 'Amanita muscaria',
        9: 'Amanita pantherina',
        10: 'Amanita persicina',
        11: 'Amanita phalloides',
        12: 'Amanita rubescens',
        13: 'Amanita velosa',
        14: 'Apioperdon pyriforme',
        15: 'Armillaria borealis',
        16: 'Armillaria mellea',
        17: 'Armillaria tabescens',
        18: 'Artomyces pyxidatus',
        19: 'Bjerkandera adusta',
        20: 'Bolbitius titubans',
        21: 'Boletus edulis',
        22: 'Boletus pallidus',
        23: 'Boletus reticulatus',
        24: 'Boletus rex-veris',
        25: 'Calocera viscosa',
        26: 'Calycina citrina',
        27: 'Cantharellus californicus',
        28: 'Cantharellus cibarius',
        29: 'Cantharellus cinnabarinus',
        30: 'Cerioporus squamosus',
        31: 'Cetraria islandica',
        32: 'Chlorociboria aeruginascens',
        33: 'Chlorophyllum brunneum',
        34: 'Chlorophyllum molybdites',
        35: 'Chondrostereum purpureum',
        36: 'Cladonia fimbriata',
        37: 'Cladonia rangiferina',
        38: 'Cladonia stellaris',
        39: 'Clitocybe nebularis',
        40: 'Clitocybe nuda',
        41: 'Coltricia perennis',
        42: 'Coprinellus disseminatus',
        43: 'Coprinellus micaceus',
        44: 'Coprinopsis atramentaria',
        45: 'Coprinopsis lagopus',
        46: 'Coprinus comatus',
        47: 'Crucibulum laeve',
        48: 'Cryptoporus volvatus',
        49: 'Daedaleopsis confragosa',
        50: 'Daedaleopsis tricolor',
        51: 'Entoloma abortivum',
        52: 'Evernia mesomorpha',
        53: 'Evernia prunastri',
        54: 'Flammulina velutipes',
        55: 'Fomes fomentarius',
        56: 'Fomitopsis betulina',
        57: 'Fomitopsis mounceae',
        58: 'Fomitopsis pinicola',
        59: 'Galerina marginata',
        60: 'Ganoderma applanatum',
        61: 'Ganoderma curtisii',
        62: 'Ganoderma oregonense',
        63: 'Ganoderma tsugae',
        64: 'Gliophorus psittacinus',
        65: 'Gloeophyllum sepiarium',
        66: 'Graphis scripta',
        67: 'Grifola frondosa',
        68: 'Gymnopilus luteofolius',
        69: 'Gyromitra esculenta',
        70: 'Gyromitra gigas',
        71: 'Gyromitra infula',
        72: 'Hericium coralloides',
        73: 'Hericium erinaceus',
        74: 'Hygrophoropsis aurantiaca',
        75: 'Hypholoma fasciculare',
        76: 'Hypholoma lateritium',
        77: 'Hypogymnia physodes',
        78: 'Hypomyces lactifluorum',
        79: 'Imleria badia',
        80: 'Inonotus obliquus',
        81: 'Ischnoderma resinosum',
        82: 'Kuehneromyces mutabilis',
        83: 'Laccaria ochropurpurea',
        84: 'Lactarius deliciosus',
        85: 'Lactarius torminosus',
        86: 'Lactarius turpis',
        87: 'Laetiporus sulphureus',
        88: 'Leccinum albostipitatum',
        89: 'Leccinum aurantiacum',
        90: 'Leccinum scabrum',
        91: 'Leccinum versipelle',
        92: 'Lepista nuda',
        93: 'Leratiomyces ceres',
        94: 'Leucoagaricus americanus',
        95: 'Leucoagaricus leucothites',
        96: 'Lobaria pulmonaria',
        97: 'Lycogala epidendrum',
        98: 'Lycoperdon perlatum',
        99: 'Lycoperdon pyriforme',
        100: 'Macrolepiota procera',
        101: 'Merulius tremellosus',
        102: 'Mutinus ravenelii',
        103: 'Mycena haematopus',
        104: 'Mycena leaiana',
        105: 'Nectria cinnabarina',
        106: 'Omphalotus illudens',
        107: 'Omphalotus olivascens',
        108: 'Panaeolus papilionaceus',
        109: 'Panellus stipticus',
        110: 'Parmelia sulcata',
        111: 'Paxillus involutus',
        112: 'Peltigera aphthosa',
        113: 'Peltigera praetextata',
        114: 'Phaeolus schweinitzii',
        115: 'Phaeophyscia orbicularis',
        116: 'Phallus impudicus',
        117: 'Phellinus igniarius',
        118: 'Phellinus tremulae',
        119: 'Phlebia radiata',
        120: 'Phlebia tremellosa',
        121: 'Pholiota aurivella',
        122: 'Pholiota squarrosa',
        123: 'Phyllotopsis nidulans',
        124: 'Physcia adscendens',
        125: 'Platismatia glauca',
        126: 'Pleurotus ostreatus',
        127: 'Pleurotus pulmonarius',
        128: 'Psathyrella candolleana',
        129: 'Pseudevernia furfuracea',
        130: 'Pseudohydnum gelatinosum',
        131: 'Psilocybe azurescens',
        132: 'Psilocybe caerulescens',
        133: 'Psilocybe cubensis',
        134: 'Psilocybe cyanescens',
        135: 'Psilocybe ovoideocystidiata',
        136: 'Psilocybe pelliculosa',
        137: 'Retiboletus ornatipes',
        138: 'Rhytisma acerinum',
        139: 'Sarcomyxa serotina',
        140: 'Sarcoscypha austriaca',
        141: 'Sarcosoma globosum',
        142: 'Schizophyllum commune',
        143: 'Stereum hirsutum',
        144: 'Stereum ostrea',
        145: 'Stropharia aeruginosa',
        146: 'Stropharia ambigua',
        147: 'Suillus americanus',
        148: 'Suillus granulatus',
        149: 'Suillus grevillei',
        150: 'Suillus luteus',
        151: 'Suillus spraguei',
        152: 'Tapinella atrotomentosa',
        153: 'Trametes betulina',
        154: 'Trametes gibbosa',
        155: 'Trametes hirsuta',
        156: 'Trametes ochracea',
        157: 'Trametes versicolor',
        158: 'Tremella mesenterica',
        159: 'Trichaptum biforme',
        160: 'Tricholoma murrillianum',
        161: 'Tricholomopsis rutilans',
        162: 'Tylopilus felleus',
        163: 'Tylopilus rubrobrunneus',
        164: 'Urnula craterium',
        165: 'Verpa bohemica',
        166: 'Volvopluteus gloiocephalus',
        167: 'Vulpicida pinastri',
        168: 'Xanthoria parietina'}
    prediction=model.predict(img)
    index=np.argmax(prediction[0])
    proba=round(max(prediction[0])*100,2)
    mushroom=index_to_class.get(index)
    return mushroom,f"{proba}%"




########################## FUNCTIONS ESPECIALLY FOR THE VIT MODEL ##################################


def load_vit_model(url="https://github.com/yves-rdlb/What-is-this-Mushroom/releases/download/vit_saved_model_v0/vit_saved_model.zip") :
    os.makedirs("models", exist_ok=True)
    zip_path = "models/vit_saved_model.zip"

    # download
    r = requests.get(url, stream=True)
    with open(zip_path, "wb") as f:
        for chunk in r.iter_content(8192):
            f.write(chunk)

    # extract
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall("models")


    model_directory_path="models/vit_saved_model"
    reloaded=tf.saved_model.load(model_directory_path)
    infer=reloaded.signatures['serving_default']
    return infer

def vit_preprocess_for_predict(img_path) :
    img=Image.open(img_path)
    img=img.resize((224,224))
    arr=np.array(img).astype('float32')
    arr=arr/255.0
    arr.shape
    arr=np.expand_dims(arr,axis=0)
    arr=tf.constant(arr,dtype=tf.float32)
    return arr

def vit_predict(infer,preprocessed_img,index_to_class) :
    species_to_label = {
    "Agaricus augustus": 0,
    "Agaricus xanthodermus": 1,
    "Amanita amerirubescens": 1,
    "Amanita augusta": 1,
    "Amanita brunnescens": 1,
    "Amanita calyptroderma": 0,
    "Amanita citrina": 1,
    "Amanita flavoconia": 1,
    "Amanita muscaria": 1,
    "Amanita pantherina": 1,
    "Amanita persicina": 1,
    "Amanita phalloides": 1,
    "Amanita rubescens": 1,
    "Amanita velosa": 1,
    "Apioperdon pyriforme": 0,
    "Armillaria borealis": 0,
    "Armillaria mellea": 0,
    "Armillaria tabescens": 0,
    "Artomyces pyxidatus": 0,
    "Bjerkandera adusta": 1,
    "Bolbitius titubans": 1,
    "Boletus edulis": 0,
    "Boletus pallidus": 0,
    "Boletus reticulatus": 0,
    "Boletus rex-veris": 0,
    "Calocera viscosa": 1,
    "Calycina citrina": 1,
    "Cantharellus californicus": 0,
    "Cantharellus cibarius": 0,
    "Cantharellus cinnabarinus": 0,
    "Cerioporus squamosus": 0,
    "Cetraria islandica": 0,
    "Chlorociboria aeruginascens": 1,
    "Chlorophyllum brunneum": 1,
    "Chlorophyllum molybdites": 1,
    "Chondrostereum purpureum": 1,
    "Cladonia fimbriata": 1,
    "Cladonia rangiferina": 0,
    "Cladonia stellaris": 0,
    "Clitocybe nebularis": 1,
    "Clitocybe nuda": 0,
    "Coltricia perennis": 1,
    "Coprinellus disseminatus": 1,
    "Coprinellus micaceus": 0,
    "Coprinopsis atramentaria": 1,
    "Coprinopsis lagopus": 1,
    "Coprinus comatus": 0,
    "Crucibulum laeve": 1,
    "Cryptoporus volvatus": 1,
    "Daedaleopsis confragosa": 1,
    "Daedaleopsis tricolor": 1,
    "Entoloma abortivum": 0,
    "Evernia mesomorpha": 1,
    "Evernia prunastri": 1,
    "Flammulina velutipes": 0,
    "Fomes fomentarius": 1,
    "Fomitopsis betulina": 1,
    "Fomitopsis mounceae": 1,
    "Fomitopsis pinicola": 1,
    "Galerina marginata": 1,
    "Ganoderma applanatum": 1,
    "Ganoderma curtisii": 1,
    "Ganoderma oregonense": 1,
    "Ganoderma tsugae": 0,
    "Gliophorus psittacinus": 1,
    "Gloeophyllum sepiarium": 1,
    "Graphis scripta": 1,
    "Grifola frondosa": 0,
    "Gymnopilus luteofolius": 1,
    "Gyromitra esculenta": 1,
    "Gyromitra gigas": 1,
    "Gyromitra infula": 1,
    "Hericium coralloides": 0,
    "Hericium erinaceus": 0,
    "Hygrophoropsis aurantiaca": 1,
    "Hypholoma fasciculare": 1,
    "Hypholoma lateritium": 0,
    "Hypogymnia physodes": 1,
    "Hypomyces lactifluorum": 0,
    "Imleria badia": 0,
    "Inonotus obliquus": 0,
    "Ischnoderma resinosum": 1,
    "Kuehneromyces mutabilis": 0,
    "Laccaria ochropurpurea": 1,
    "Lactarius deliciosus": 0,
    "Lactarius torminosus": 1,
    "Lactarius turpis": 1,
    "Laetiporus sulphureus": 0,
    "Leccinum albostipitatum": 0,
    "Leccinum aurantiacum": 0,
    "Leccinum scabrum": 0,
    "Leccinum versipelle": 0,
    "Lepista nuda": 0,
    "Leratiomyces ceres": 1,
    "Leucoagaricus americanus": 1,
    "Leucoagaricus leucothites": 0,
    "Lobaria pulmonaria": 1,
    "Lycogala epidendrum": 1,
    "Lycoperdon perlatum": 0,
    "Lycoperdon pyriforme": 0,
    "Macrolepiota procera": 0,
    "Merulius tremellosus": 1,
    "Mutinus ravenelii": 1,
    "Mycena haematopus": 1,
    "Mycena leaiana": 1,
    "Nectria cinnabarina": 1,
    "Omphalotus illudens": 1,
    "Omphalotus olivascens": 1,
    "Panaeolus papilionaceus": 1,
    "Panellus stipticus": 1,
    "Parmelia sulcata": 1,
    "Paxillus involutus": 1,
    "Peltigera aphthosa": 1,
    "Peltigera praetextata": 1,
    "Phaeolus schweinitzii": 1,
    "Phaeophyscia orbicularis": 1,
    "Phallus impudicus": 0,
    "Phellinus igniarius": 1,
    "Phellinus tremulae": 1,
    "Phlebia radiata": 1,
    "Phlebia tremellosa": 1,
    "Pholiota aurivella": 1,
    "Pholiota squarrosa": 1,
    "Phyllotopsis nidulans": 1,
    "Physcia adscendens": 1,
    "Platismatia glauca": 1,
    "Pleurotus ostreatus": 0,
    "Pleurotus pulmonarius": 0,
    "Psathyrella candolleana": 1,
    "Pseudevernia furfuracea": 1,
    "Pseudohydnum gelatinosum": 0,
    "Psilocybe azurescens": 1,
    "Psilocybe caerulescens": 1,
    "Psilocybe cubensis": 1,
    "Psilocybe cyanescens": 1,
    "Psilocybe ovoideocystidiata": 1,
    "Psilocybe pelliculosa": 1,
    "Retiboletus ornatipes": 0,
    "Rhytisma acerinum": 1,
    "Sarcomyxa serotina": 0,
    "Sarcoscypha austriaca": 1,
    "Sarcosoma globosum": 1,
    "Schizophyllum commune": 1,
    "Stereum hirsutum": 1,
    "Stereum ostrea": 1,
    "Stropharia aeruginosa": 1,
    "Stropharia ambigua": 1,
    "Suillus americanus": 0,
    "Suillus granulatus": 0,
    "Suillus grevillei": 0,
    "Suillus luteus": 0,
    "Suillus spraguei": 0,
    "Tapinella atrotomentosa": 1,
    "Trametes betulina": 1,
    "Trametes gibbosa": 1,
    "Trametes hirsuta": 1,
    "Trametes ochracea": 1,
    "Trametes versicolor": 1,
    "Tremella mesenterica": 0,
    "Trichaptum biforme": 1,
    "Tricholoma murrillianum": 0,
    "Tricholomopsis rutilans": 0,
    "Tylopilus felleus": 1,
    "Tylopilus rubrobrunneus": 1,
    "Urnula craterium": 1,
    "Verpa bohemica": 1,
    "Volvopluteus gloiocephalus": 0,
    "Vulpicida pinastri": 1,
    "Xanthoria parietina": 1,
    }

    index_to_class={0: 'Agaricus augustus',
        1: 'Agaricus xanthodermus',
        2: 'Amanita amerirubescens',
        3: 'Amanita augusta',
        4: 'Amanita brunnescens',
        5: 'Amanita calyptroderma',
        6: 'Amanita citrina',
        7: 'Amanita flavoconia',
        8: 'Amanita muscaria',
        9: 'Amanita pantherina',
        10: 'Amanita persicina',
        11: 'Amanita phalloides',
        12: 'Amanita rubescens',
        13: 'Amanita velosa',
        14: 'Apioperdon pyriforme',
        15: 'Armillaria borealis',
        16: 'Armillaria mellea',
        17: 'Armillaria tabescens',
        18: 'Artomyces pyxidatus',
        19: 'Bjerkandera adusta',
        20: 'Bolbitius titubans',
        21: 'Boletus edulis',
        22: 'Boletus pallidus',
        23: 'Boletus reticulatus',
        24: 'Boletus rex-veris',
        25: 'Calocera viscosa',
        26: 'Calycina citrina',
        27: 'Cantharellus californicus',
        28: 'Cantharellus cibarius',
        29: 'Cantharellus cinnabarinus',
        30: 'Cerioporus squamosus',
        31: 'Cetraria islandica',
        32: 'Chlorociboria aeruginascens',
        33: 'Chlorophyllum brunneum',
        34: 'Chlorophyllum molybdites',
        35: 'Chondrostereum purpureum',
        36: 'Cladonia fimbriata',
        37: 'Cladonia rangiferina',
        38: 'Cladonia stellaris',
        39: 'Clitocybe nebularis',
        40: 'Clitocybe nuda',
        41: 'Coltricia perennis',
        42: 'Coprinellus disseminatus',
        43: 'Coprinellus micaceus',
        44: 'Coprinopsis atramentaria',
        45: 'Coprinopsis lagopus',
        46: 'Coprinus comatus',
        47: 'Crucibulum laeve',
        48: 'Cryptoporus volvatus',
        49: 'Daedaleopsis confragosa',
        50: 'Daedaleopsis tricolor',
        51: 'Entoloma abortivum',
        52: 'Evernia mesomorpha',
        53: 'Evernia prunastri',
        54: 'Flammulina velutipes',
        55: 'Fomes fomentarius',
        56: 'Fomitopsis betulina',
        57: 'Fomitopsis mounceae',
        58: 'Fomitopsis pinicola',
        59: 'Galerina marginata',
        60: 'Ganoderma applanatum',
        61: 'Ganoderma curtisii',
        62: 'Ganoderma oregonense',
        63: 'Ganoderma tsugae',
        64: 'Gliophorus psittacinus',
        65: 'Gloeophyllum sepiarium',
        66: 'Graphis scripta',
        67: 'Grifola frondosa',
        68: 'Gymnopilus luteofolius',
        69: 'Gyromitra esculenta',
        70: 'Gyromitra gigas',
        71: 'Gyromitra infula',
        72: 'Hericium coralloides',
        73: 'Hericium erinaceus',
        74: 'Hygrophoropsis aurantiaca',
        75: 'Hypholoma fasciculare',
        76: 'Hypholoma lateritium',
        77: 'Hypogymnia physodes',
        78: 'Hypomyces lactifluorum',
        79: 'Imleria badia',
        80: 'Inonotus obliquus',
        81: 'Ischnoderma resinosum',
        82: 'Kuehneromyces mutabilis',
        83: 'Laccaria ochropurpurea',
        84: 'Lactarius deliciosus',
        85: 'Lactarius torminosus',
        86: 'Lactarius turpis',
        87: 'Laetiporus sulphureus',
        88: 'Leccinum albostipitatum',
        89: 'Leccinum aurantiacum',
        90: 'Leccinum scabrum',
        91: 'Leccinum versipelle',
        92: 'Lepista nuda',
        93: 'Leratiomyces ceres',
        94: 'Leucoagaricus americanus',
        95: 'Leucoagaricus leucothites',
        96: 'Lobaria pulmonaria',
        97: 'Lycogala epidendrum',
        98: 'Lycoperdon perlatum',
        99: 'Lycoperdon pyriforme',
        100: 'Macrolepiota procera',
        101: 'Merulius tremellosus',
        102: 'Mutinus ravenelii',
        103: 'Mycena haematopus',
        104: 'Mycena leaiana',
        105: 'Nectria cinnabarina',
        106: 'Omphalotus illudens',
        107: 'Omphalotus olivascens',
        108: 'Panaeolus papilionaceus',
        109: 'Panellus stipticus',
        110: 'Parmelia sulcata',
        111: 'Paxillus involutus',
        112: 'Peltigera aphthosa',
        113: 'Peltigera praetextata',
        114: 'Phaeolus schweinitzii',
        115: 'Phaeophyscia orbicularis',
        116: 'Phallus impudicus',
        117: 'Phellinus igniarius',
        118: 'Phellinus tremulae',
        119: 'Phlebia radiata',
        120: 'Phlebia tremellosa',
        121: 'Pholiota aurivella',
        122: 'Pholiota squarrosa',
        123: 'Phyllotopsis nidulans',
        124: 'Physcia adscendens',
        125: 'Platismatia glauca',
        126: 'Pleurotus ostreatus',
        127: 'Pleurotus pulmonarius',
        128: 'Psathyrella candolleana',
        129: 'Pseudevernia furfuracea',
        130: 'Pseudohydnum gelatinosum',
        131: 'Psilocybe azurescens',
        132: 'Psilocybe caerulescens',
        133: 'Psilocybe cubensis',
        134: 'Psilocybe cyanescens',
        135: 'Psilocybe ovoideocystidiata',
        136: 'Psilocybe pelliculosa',
        137: 'Retiboletus ornatipes',
        138: 'Rhytisma acerinum',
        139: 'Sarcomyxa serotina',
        140: 'Sarcoscypha austriaca',
        141: 'Sarcosoma globosum',
        142: 'Schizophyllum commune',
        143: 'Stereum hirsutum',
        144: 'Stereum ostrea',
        145: 'Stropharia aeruginosa',
        146: 'Stropharia ambigua',
        147: 'Suillus americanus',
        148: 'Suillus granulatus',
        149: 'Suillus grevillei',
        150: 'Suillus luteus',
        151: 'Suillus spraguei',
        152: 'Tapinella atrotomentosa',
        153: 'Trametes betulina',
        154: 'Trametes gibbosa',
        155: 'Trametes hirsuta',
        156: 'Trametes ochracea',
        157: 'Trametes versicolor',
        158: 'Tremella mesenterica',
        159: 'Trichaptum biforme',
        160: 'Tricholoma murrillianum',
        161: 'Tricholomopsis rutilans',
        162: 'Tylopilus felleus',
        163: 'Tylopilus rubrobrunneus',
        164: 'Urnula craterium',
        165: 'Verpa bohemica',
        166: 'Volvopluteus gloiocephalus',
        167: 'Vulpicida pinastri',
        168: 'Xanthoria parietina'}
    y=infer(preprocessed_img)
    prediction=(list(y.values())[0].numpy()[0])
    index=np.argmax(prediction)
    proba=round(max(prediction)*100,2)
    mushroom=index_to_class.get(index)
    edibility=species_to_label[mushroom]
    if edibility==1 : edibility='not edible'
    else : edibility='edible'
    return mushroom,edibility,f"{proba}%"
